### ISSUE TITLE
求助ERROR: Traceback (most recent call last):   File "main.py", line 77, in main IndexError: list index out of range

### ISSUE THREAD

**Issue by feizhaiyuyan** [Yudaotor/Riot-Accounts-AutoChangePassword#13]
日志和运行结果如下，
![QQ图片20230815012914](https://github.com/Yudaotor/Riot-Accounts-AutoChangePassword/assets/142253405/01f5dc1a-4405-43f9-b9da-64107eae865b)
之前运行成功过，现在启动程序出现问题，求助如何解决，拜托大佬了

**Comment by Yudaotor** [comment]
你账密文件格式不对吧

**Comment by feizhaiyuyan** [comment]
> 你填写密码文件正确格式吧

还真是，没注意到
