### ISSUE TITLE
接受Cookies發生錯誤

### ISSUE THREAD

**Issue by feizhaiyuyan** [Yudaotor/Riot-Accounts-AutoChangePassword#18]
![QQ图片20231107093336](https://github.com/Yudaotor/Riot-Accounts-AutoChangePassword/assets/142253405/453d2ce9-1a87-4757-bfa7-678063ba3972)
情况如图所示
软件打开浏览器后在输入账密的界面就停止

**Comment by Yudaotor** [comment]
提供log日志

**Comment by feizhaiyuyan** [comment]
好的
[AutoChangePassword-Nov-07-09-34.log](https://github.com/Yudaotor/Riot-Accounts-AutoChangePassword/files/13277203/AutoChangePassword-Nov-07-09-34.log)
