### ISSUE TITLE
网易163邮箱获取验证码失败问题解决

### ISSUE THREAD

**Issue by pathing** [Yudaotor/Riot-Accounts-AutoChangePassword#6]
使用163邮箱，必须在select之前上传客户端身份信息，否则会报错失败，下面是解决方法：
在Handler.py加入以下代码：
`def setid(conn, username):
    imaplib.Commands['ID'] = 'AUTH'
    args = ("name", username, "contact", username, "version", "1.0.0", "vendor", "myclient")
    typ, dat = conn._simple_command('ID', '("' + '" "'.join(args) + '")')
    `
然后在`M.login(username, password)`后面加上`setid(M, username)`。如截图：
![1684172843148(1)](https://github.com/Yudaotor/Riot-Accounts-AutoChangePassword/assets/11513848/f26f1573-4fe4-482e-95a8-6735abb27e1f)

**Comment by Yudaotor** [comment]
方便提交一个pr吗

**Comment by pathing** [comment]
> 方便提交一个pr吗

好的，我晚上找时间测下其他邮箱的兼容性再提交

**Comment by pathing** [comment]
已提交

**Comment by Yudaotor** [comment]
> 已提交

好的，有空再看一下

**Comment by Yudaotor** [comment]
已更新
